name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r login/requirements.txt
          pip install flake8

      - name: Syntax check (compileall)
        run: |
          python -m compileall -q login

      - name: Lint with flake8
        run: |
          flake8 login --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 login --count --exit-zero --max-complexity=25 --max-line-length=120 --statistics


